Study nurse menu feature
healthcare-it-solutions/picos pull request #112
Opened 2023-04-11 08:09 UTC by mustiwebp

What the title says.

2023-04-11 10:40 UTC, S1rDan commented
When I try to edit a patient I'm getting a LateInitializationError: Field '_weightBMI@99384301' has not been initialized.

2023-04-14 09:25 UTC, S1rDan requested changes

2023-04-14 09:25 UTC, S1rDan commented on lib/screens/study_nurse_screen/menu_screen/patients_list.dart
> +                            .patientObjectId) {
This process is too expensive and gets even more so if the amount of data grows.

It should be handled differently:
Either you build a new query and let the database handle that issue by applying filters etc.
or you allow all Patient objects and let the user fill the missing information when editing the entry.

2023-04-14 09:25 UTC, S1rDan commented on lib/widgets/picos_list_card.dart
There are more changes to be made.
If you look closely the singular button is not symmetric.

2023-04-14 09:52 UTC, mustiwebp commented on lib/screens/study_nurse_screen/menu_screen/patients_list.dart
> +                itemCount: statePatientData.objectsList.length,
Well, I took the minimum of both.

2023-04-17 09:23 UTC, mustiwebp commented on lib/screens/study_nurse_screen/menu_screen/add_patient_screen.dart
I think it's easier than your way.

2023-04-18 06:14 UTC, S1rDan commented on lib/screens/study_nurse_screen/menu_screen/patients_list.dart
> +                itemCount: statePatientData.objectsList.length,
Thing is, is it granted that the PatientData count ist always the same as the Patients count to be shown?

2023-04-28 09:52 UTC, closed without merging