Minor Fixes
healthcare-it-solutions/picos pull request #15
Opened 2022-08-11 06:17 UTC by S1rDan

Fixing some issues the linter is coming up with.

2022-08-12 08:20 UTC, mustiwebp reviewed
PR is fine from my side!

2022-08-12 13:25 UTC, inchw0rm requested changes

2022-08-12 13:25 UTC, inchw0rm commented on lib/l10n/app_de.arb
> +    "entryValidEmail": "Bitte Sie eine gültige E-Mail-Adresse ein!",
The message on line 56 is still not right

2022-08-12 13:26 UTC, inchw0rm commented on lib/l10n/app_de.arb
> +    "entryValidEmail": "Bitte Sie eine gültige E-Mail-Adresse ein!",
It's also fine from my side, please squash and merge when ready.

2022-08-15 07:00 UTC, S1rDan commented
I've created the change. I can't merge that myself due to lack of rights.

2022-08-16 08:38 UTC, merged