Buttons put on the right side & Divider added
healthcare-it-solutions/picos pull request #96
Opened 2023-03-15 13:06 UTC by mustiwebp

What the title says.

2023-03-17 08:11 UTC, S1rDan requested changes

2023-03-17 08:11 UTC, S1rDan commented on lib/widgets/picos_radio_select.dart
The divider are not quite there yet. Look at PainScale or the Mockup to see, how it should look like.

2023-03-20 11:38 UTC, mustiwebp commented on lib/widgets/picos_radio_select.dart
I added some adjustments

2023-03-21 06:48 UTC, S1rDan requested changes

2023-03-21 06:48 UTC, S1rDan commented on lib/widgets/picos_radio_select.dart
> +      children: <ListView>[
Well two things:
1. The ListView makes the Column redundant. You should only use one or the other.
2. THe ListView makes the content scrollable even if it shouldn't scroll. Try to scroll within a PicosRadioSelect and you notice, the overscroll effect.

2023-03-21 10:19 UTC, S1rDan commented on lib/widgets/picos_radio_select.dart
There is another visual bug I noticed:

The ink splash (the effect if you hold down on an item) doesn't appear over the whole width of the parent widget anymore, like it does with SleepQuality and PainScale.

2023-03-21 11:47 UTC, mustiwebp commented on lib/widgets/picos_radio_select.dart
Should be solved now.

2023-03-22 06:30 UTC, S1rDan requested changes

2023-03-22 06:30 UTC, S1rDan commented on lib/widgets/picos_radio_select.dart
> +  final double _distance = 15;
```suggestion
  static const double _distance = 15;
```
One more optimization.

2023-03-22 06:30 UTC, S1rDan commented on lib/widgets/picos_radio_select.dart
> +          contentPadding: EdgeInsets.symmetric(horizontal: _distance),
```suggestion
          contentPadding: const EdgeInsets.symmetric(horizontal: _distance),
```

2023-03-22 06:30 UTC, S1rDan commented on lib/widgets/picos_radio_select.dart
> +        return Divider(
```suggestion
        return const Divider(
```

2023-03-22 07:34 UTC, S1rDan approved these changes

2023-03-22 07:36 UTC, merged

2023-03-22 07:36 UTC, S1rDan reviewed
Should be fine now.