Cover pages refactoring
healthcare-it-solutions/picos pull request #97
Opened 2023-03-20 10:47 UTC by mustiwebp

What the title says.

2023-03-21 07:18 UTC, S1rDan commented on lib/screens/questionaire_screen/widgets/last_cover.dart
What is the point of this widget?
It seems redundant.

2023-03-21 07:41 UTC, mustiwebp commented on lib/screens/questionaire_screen/widgets/last_cover.dart
It is the widget specially for the last page of the questionnaire. It is different from the other cover pages thus I created an own widget for that.

2023-03-21 07:45 UTC, S1rDan requested changes

2023-03-21 07:45 UTC, S1rDan commented on lib/screens/questionaire_screen/widgets/last_cover.dart
> +                      assetName: 'assets/Tipp.svg',
The colors aren't rendered for this SVG.
Check this out: [https://stackoverflow.com/a/65033951](https://stackoverflow.com/a/65033951)
I've tried it. After preparing the SVG with this tool and removing the colorFilter from PicosSvgIcon, the Picture gets rendered correctly.
I would suggest to try this solution for all SVG's and watch what happens.

2023-03-21 07:51 UTC, S1rDan commented on lib/screens/questionaire_screen/widgets/last_cover.dart
It just adds two more widgets (SizedBox and Container) to to the very same copy pasted Column. It doesn't do anything else.

2023-03-22 08:08 UTC, S1rDan requested changes
Almost done.

2023-03-22 09:02 UTC, merged